// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBldyDeenMjEQPAA7gKT8iAP3aBBHhxrvw',
    appId: '1:224229507477:android:6514cb5b53e6f790b5f69c',
    messagingSenderId: '224229507477',
    projectId: 'b2-people',
    storageBucket: 'b2-people.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNVVi7DUktZDAoh-_SHk-711VY9nXrk00',
    appId: '1:224229507477:ios:7671dfb526540e8fb5f69c',
    messagingSenderId: '224229507477',
    projectId: 'b2-people',
    storageBucket: 'b2-people.firebasestorage.app',
    androidClientId: '224229507477-ulobrj6ip5hldg4ovo6n9r1uc22gvt1d.apps.googleusercontent.com',
    iosClientId: '224229507477-9a3n70iqnlu647hr51ae694s4uvn88d9.apps.googleusercontent.com',
    iosBundleId: 'br.com.b2-people.b2People',
  );
}
